[phases.install]
cmds = ["npm install --ignore-scripts"]

[phases.build]
cmds = ["apt-get update && apt-get install -y libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev libpixman-1-dev && npm rebuild canvas"]

[start]
cmd = "node index.js"
