[build]
builder = "NIXPACKS"
buildCommand = "npm install --ignore-scripts && npm rebuild canvas --build-from-source"

[deploy]
startCommand = "node index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
